name: Build and Release

on:
  push:
    branches: [ v5.0.0 ]
    tags:
      - 'v*.*.*'
  pull_request:
    branches: [ v5.0.0 ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Required for MinVer to work correctly
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    
    - name: Extract version from git tag
      id: get_version
      shell: pwsh
      run: |
        if ($env:GITHUB_REF -match 'refs/tags/v(.+)') {
          $version = $matches[1]
          echo "VERSION=$version" >> $env:GITHUB_OUTPUT
          echo "Creating release for version $version"
        } else {
          echo "VERSION=0.0.0" >> $env:GITHUB_OUTPUT
          echo "No version tag found, using 0.0.0"
        }
    
    - name: Restore NuGet packages
      run: dotnet restore "Source\EasyBrailleEditApp\EasyBrailleEditApp.sln"
      
    - name: Build solution
      run: dotnet build "Source\EasyBrailleEditApp\EasyBrailleEditApp.sln" --configuration Release --no-restore
      
    - name: Publish EasyBrailleEdit
      run: dotnet publish "Source\EasyBrailleEditApp\EasyBrailleEdit\EasyBrailleEdit.csproj" --configuration Release --no-build --output publish\EasyBrailleEdit
    
    - name: Publish Txt2Brl
      run: dotnet publish "Source\EasyBrailleEditApp\Txt2Brl\Txt2Brl.csproj" --configuration Release --no-build --output publish\Txt2Brl
      
    - name: Zip EasyBrailleEdit
      run: Compress-Archive -Path .\publish\EasyBrailleEdit\* -DestinationPath .\publish\EasyBrailleEdit-v${{ steps.get_version.outputs.VERSION }}.zip
      shell: pwsh
      
    - name: Zip Txt2Brl
      run: Compress-Archive -Path .\publish\Txt2Brl\* -DestinationPath .\publish\Txt2Brl-v${{ steps.get_version.outputs.VERSION }}.zip
      shell: pwsh
      
    - name: Upload EasyBrailleEdit artifacts
      uses: actions/upload-artifact@v4
      with:
        name: EasyBrailleEdit
        path: publish\EasyBrailleEdit\
        
    - name: Upload Txt2Brl artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Txt2Brl
        path: publish\Txt2Brl\
        
    - name: Create GitHub Release
      if: startsWith(github.ref, 'refs/tags/v')
      uses: softprops/action-gh-release@v2
      with:
        files: |
          publish\EasyBrailleEdit-v${{ steps.get_version.outputs.VERSION }}.zip
          publish\Txt2Brl-v${{ steps.get_version.outputs.VERSION }}.zip
        name: 易點雙視 v${{ steps.get_version.outputs.VERSION }}
        body: |
          # 易點雙視 v${{ steps.get_version.outputs.VERSION }}
          
          易點雙視（EasyBrailleEdit）是一個 Windows 應用程式，主要用途是編輯與列印雙視教材，以供視障朋友摸讀。
          
          ## 本版更新內容
          
          <!-- 請在這裡填寫更新內容 -->
          
          ## 下載檔案說明
          
          - **EasyBrailleEdit-v${{ steps.get_version.outputs.VERSION }}.zip**: 雙視點字編輯器主程式
          - **Txt2Brl-v${{ steps.get_version.outputs.VERSION }}.zip**: 文字轉點字命令列工具
        draft: true